### ISSUE TITLE
Add `src/ui/package-lock.json` to `.gitignore` file.

### ISSUE THREAD

**Issue by YunSangJun** [kubernetes-helm/monocular#458]
I've got error message while `make docker-build` from `monocular ui`.
I found same issue. (https://github.com/angular/angular-cli/issues/6641)
I success to the build after removed `src/ui/package-lock.json`.
```
yarn run xxx
yarn run v1.7.0
$ ng build --prod --aot --progress=false --output-path rootfs/dist
Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sangjunyun/git/zcp-catalog-ui/node_modules/html-webpack-plugin/lib/compiler.js:11:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sangjunyun/git/zcp-catalog-ui/node_modules/html-webpack-plugin/index.js:7:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [compile-aot] Error 1
```

So i think that `src/ui/package-lock.json` should be added to `.gitignore` file.
https://github.com/YunSangJun/monocular/commit/947b307aece8609813b556ac9816e926f2fcb768

**Comment by Jaskaranbir** [comment]
These issues can also arise due to "version inconsistency" (for the sake of not knowing a better term here).

Did you try `npm install webpack` before removing `package-lock.json`? If that fixes the issue, we can just update the version in `package.json` and `package-lock.json` instead of removing them.
